"""empty message

Revision ID: b157353dfa6e
Revises: 
Create Date: 2024-02-10 17:31:03.780299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b157353dfa6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_identifier', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_record')
    # ### end Alembic commands ###
